### ISSUE TITLE
Unable to generate QR code

### ISSUE THREAD

**Issue by mayanknahata007** [tueit/Swiss-Accounting-Integration#10]
In order to Setup QR Bill to Working Following Things are Required

Create A Company With Proper Address - 
![Screenshot 2021-08-11 at 11 19 38 AM](https://user-images.githubusercontent.com/88381410/128976334-74ee906f-38ff-41a2-9c5b-dc958b283b41.png)

Create A Customer with Proper Address and Language -
![Screenshot 2021-08-11 at 11 05 54 AM](https://user-images.githubusercontent.com/88381410/128976203-6c9926f2-12d3-46df-a106-f41e4880805e.png)

Create A Bank Account For Company with IBAN -
![Screenshot 2021-08-11 at 11 05 29 AM](https://user-images.githubusercontent.com/88381410/128976176-34312878-6652-4a90-8fff-f18be61e4bc8.png)

Add Entry in Swiss QR Bill Settings for Company -
![Screenshot 2021-08-11 at 11 05 10 AM](https://user-images.githubusercontent.com/88381410/128976373-26c43440-17dd-4a53-bccb-10f8ad67874c.png)

<b>I have completed all steps mentioned in the read me guide. Still, I'm unable to generate the QR bill for it.</b>
![Screenshot 2021-08-11 at 11 05 48 AM](https://user-images.githubusercontent.com/88381410/128976614-997f0bfc-8882-44cc-ae73-4170b64bec06.png)

**Comment by akazyti** [comment]
![screenshot-ans](https://user-images.githubusercontent.com/30781942/128979839-2c062032-6263-4336-8899-10037fa83aad.png)

I Think javaScript is not properly build during installation & that's why it is not able to get the javaScript

**Comment by akazyti** [comment]
[ACC-SINV-2021-00014-QRBILL.pdf](https://github.com/tueit/Swiss-Accounting-Integration/files/6966381/ACC-SINV-2021-00014-QRBILL.pdf)
This is the PDF currently We are able to generate

**Comment by grynn-in** [comment]
We have pre-compiled the library and added to the github. So it doesnt need the webpack to generate it. This issue is solved.
