### ISSUE TITLE
Add require documents to this project as notes.

### ISSUE THREAD

**Issue by grynn-in** [tueit/Swiss-Accounting-Integration#4]
@wojosc would you kindly copy paste the requirement / docs?

**Comment by wojosc** [comment]
@grynn-in I have sent you an invite to our documentation I will post everything there for you. Let me know if that all works

**Comment by wojosc** [comment]
@grynn-in I have sent you a invite to our platform. you'll find the docs on this page:
https://handbuch.tueit.de/books/00193-swiss-accounting-integration/page/vorbereitung

also you'll find some notes from my call with frappe today:
https://handbuch.tueit.de/books/00193-swiss-accounting-integration/page/asbtimmung-mayank-3007

**Comment by grynn-in** [comment]
Strange, get a 404 error.

**Comment by grynn-in** [comment]
solved.
